import subprocess, os
os.chdir(r'C:\Users\smartan\source\code\code\portfolio-ai\dg-video-scrubber')

print("=" * 80)
print("STEP 1: Running node setup.mjs")
print("=" * 80)
result = subprocess.run(['node', 'setup.mjs'], capture_output=True, text=True)
print('SETUP STDOUT:', result.stdout)
print('SETUP STDERR:', result.stderr)
print('SETUP RETURNCODE:', result.returncode)

print("\n" + "=" * 80)
print("STEP 2: Running npm install")
print("=" * 80)
result2 = subprocess.run(['npm', 'install'], capture_output=True, text=True, shell=True, cwd=r'C:\Users\smartan\source\code\code\portfolio-ai\dg-video-scrubber')
print('NPM INSTALL STDOUT:', result2.stdout[-3000:])
print('NPM INSTALL STDERR:', result2.stderr[-2000:])
print('NPM INSTALL RETURNCODE:', result2.returncode)

print("\n" + "=" * 80)
print("STEP 3: Running npm run build")
print("=" * 80)
result3 = subprocess.run(['npm', 'run', 'build'], capture_output=True, text=True, shell=True, cwd=r'C:\Users\smartan\source\code\code\portfolio-ai\dg-video-scrubber')
print('BUILD STDOUT:', result3.stdout)
print('BUILD STDERR:', result3.stderr)
print('BUILD RETURNCODE:', result3.returncode)
